/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 forest_clearing_1_top_skybox-4k.glb -T 
Files: forest_clearing_1_top_skybox-4k.glb [12.46MB] > F:\My Documents\Sites games\trash-chute\public\models\forest_clearing_1_top_skybox-4k-transformed.glb [85.54KB] (99%)
Author: Luis Vidal (https://sketchfab.com/Luis_Vidal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/forest-clearing-1-top-skybox-ed2c72a25b834f0aac84c4e91b9864cc
Title: Forest Clearing 1 Top Skybox
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/forest_clearing_1_top_skybox-4k-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_Skybox_0.geometry} material={materials.Skybox} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/forest_clearing_1_top_skybox-4k-transformed.glb')
