/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Burger.glb -T 
Files: Burger.glb [57.12KB] > F:\My Documents\Sites games\trash-chute\public\models\Burger-transformed.glb [6.84KB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelBurger(props) {
  const { nodes, materials } = useGLTF('models/Burger-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Burger.geometry} material={materials.PaletteMaterial001} rotation={[0, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('models/Burger-transformed.glb')
