/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Can.glb -T 
Files: Can.glb [25.46KB] > F:\My Documents\Sites games\trash-chute\public\models\Can-transformed.glb [3.94KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelCan(props) {
  const { nodes, materials } = useGLTF('models/Can-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Can_Closed_1.geometry} material={materials.LightGrey} />
        <mesh geometry={nodes.Can_Closed_2.geometry} material={materials.Grey} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Can-transformed.glb')
