/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dumpster.glb -T 
Files: Dumpster.glb [19.78KB] > F:\My Documents\Sites games\trash-chute\public\models\Dumpster-transformed.glb [4.48KB] (77%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelDumpster(props) {
  const { nodes, materials } = useGLTF('models/Dumpster-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={58.6}>
        <mesh geometry={nodes.TrashContainer_1.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.TrashContainer_2.geometry} material={materials.Green} />
        <mesh geometry={nodes.TrashContainer_3.geometry} material={materials.Grey} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Dumpster-transformed.glb')
