/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 models\flag-red.glb --output output\flag-red.js --transform 
Files: models\flag-red.glb [3.73KB] > E:\Downloads\kenney_minigolf-kit\JSX\output\flag-red-transformed.glb [3.76KB] (-1%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
const link = `${process.env.NEXT_PUBLIC_CDN}games/Assets/KennyNL/MiniGolf/Models/flag-red-transformed.glb`;

export function ModelKennyNLMiniGolfFlagRed(props) {
  const { nodes, materials } = useGLTF(link)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['flag-red_1'].geometry} material={materials.colormap} scale={0.5} />
    </group>
  )
}

useGLTF.preload(link)
