/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 forest_clearing_1_top_skybox.glb -T 
Files: forest_clearing_1_top_skybox.glb [854.4KB] > F:\My Documents\Sites games\trash-chute\public\models\forest_clearing_1_top_skybox-transformed.glb [84.92KB] (90%)
Author: Luis Vidal (https://sketchfab.com/Luis_Vidal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/forest-clearing-1-top-skybox-ed2c72a25b834f0aac84c4e91b9864cc
Title: Forest Clearing 1 Top Skybox
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useStore } from '@/hooks/useStore';

const HIGH_MODEL = 'models/forest_clearing_1_top_skybox-4k.glb'
const LOW_MODEL = 'models/forest_clearing_1_top_skybox-4k-transformed.glb'

export function ModelSkybox(props) {

  const darkMode = useStore(state => state.darkMode);

  const graphicsQuality = useStore(state => state.graphicsQuality);
  const modelPath = graphicsQuality === 'High' ? HIGH_MODEL : LOW_MODEL;

  const { nodes, materials } = useGLTF(modelPath)

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere_Skybox_0.geometry}
        material={materials.Skybox}
        material-color={darkMode ? '#757575' : '#ffffff'}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload(HIGH_MODEL)
useGLTF.preload(LOW_MODEL)
