/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Spiky Ball.glb -T 
Files: Spiky Ball.glb [28.83KB] > F:\My Documents\Sites games\trash-chute\public\models\Spiky Ball-transformed.glb [7.45KB] (74%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelSpikyBall(props) {
  const { nodes, materials } = useGLTF('models/Spiky Ball-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.SpikyBall_1.geometry} material={materials.Black} />
        <mesh geometry={nodes.SpikyBall_2.geometry} material={materials.DarkMetal} />
        <mesh geometry={nodes.SpikyBall_3.geometry} material={materials.Metal} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Spiky Ball-transformed.glb')
