/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 stylized_rock.glb -T 
Files: stylized_rock.glb [1.4MB] > F:\My Documents\Sites games\trash-chute\public\models\stylized_rock-transformed.glb [139.46KB] (90%)
Author: DubbleSnup (https://sketchfab.com/dubblesnup)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-rock-f0309cd2e4a347c3996cd7d887cd2d4a
Title: Stylized Rock
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelStylizedRock(props) {
  const { nodes, materials } = useGLTF('models/stylized_rock-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.lp_Material001_0.geometry} material={materials['Material.001']} position={[0.141, -0.043, 0.143]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/stylized_rock-transformed.glb')
